# Generated by Django 2.1.3 on 2019-01-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190105_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessageRely',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='parent',
        ),
        migrations.AddField(
            model_name='directmessagerely',
            name='dm_reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_reply', to='users.DirectMessage'),
        ),
    ]
