# Generated by Django 2.1.3 on 2019-01-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190105_1912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DirectMessageRely',
            new_name='DirectMessageReply',
        ),
    ]
