# Generated by Django 2.1.3 on 2019-01-03 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20181231_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.Comment'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='sub_reply',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.Reply'),
        ),
    ]
