# Generated by Django 2.1.3 on 2019-01-03 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20190103_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='sub_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Reply'),
        ),
    ]
